export type Airport = { code: string; city: string; name: string; country: string };

export const AIRPORTS: Airport[] = [
  { code: 'JFK', city: 'New York', name: 'John F. Kennedy Intl', country: 'USA' },
  { code: 'LGA', city: 'New York', name: 'LaGuardia', country: 'USA' },
  { code: 'EWR', city: 'Newark', name: 'Newark Liberty Intl', country: 'USA' },
  { code: 'LAX', city: 'Los Angeles', name: 'Los Angeles Intl', country: 'USA' },
  { code: 'SFO', city: 'San Francisco', name: 'San Francisco Intl', country: 'USA' },
  { code: 'SAN', city: 'San Diego', name: 'San Diego Intl', country: 'USA' },
  { code: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma Intl', country: 'USA' },
  { code: 'ORD', city: 'Chicago', name: "O'Hare Intl", country: 'USA' },
  { code: 'MDW', city: 'Chicago', name: 'Midway Intl', country: 'USA' },
  { code: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson', country: 'USA' },
  { code: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth Intl', country: 'USA' },
  { code: 'IAH', city: 'Houston', name: 'George Bush Intl', country: 'USA' },
  { code: 'MIA', city: 'Miami', name: 'Miami Intl', country: 'USA' },
  { code: 'MCO', city: 'Orlando', name: 'Orlando Intl', country: 'USA' },
  { code: 'LAS', city: 'Las Vegas', name: 'Harry Reid Intl', country: 'USA' },
  { code: 'PHX', city: 'Phoenix', name: 'Sky Harbor Intl', country: 'USA' },
  { code: 'DEN', city: 'Denver', name: 'Denver Intl', country: 'USA' },
  { code: 'BOS', city: 'Boston', name: 'Logan Intl', country: 'USA' },
  { code: 'DCA', city: 'Washington', name: 'Reagan National', country: 'USA' },
  { code: 'IAD', city: 'Washington', name: 'Dulles Intl', country: 'USA' },
  { code: 'PHL', city: 'Philadelphia', name: 'Philadelphia Intl', country: 'USA' },
  { code: 'DTW', city: 'Detroit', name: 'Detroit Metro', country: 'USA' },
  { code: 'MSP', city: 'Minneapolis', name: 'Minneapolis-St Paul', country: 'USA' },
  { code: 'CLT', city: 'Charlotte', name: 'Charlotte Douglas', country: 'USA' },
  { code: 'SLC', city: 'Salt Lake City', name: 'Salt Lake City Intl', country: 'USA' },
  { code: 'PDX', city: 'Portland', name: 'Portland Intl', country: 'USA' },
  { code: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye Intl', country: 'USA' },
  { code: 'AUS', city: 'Austin', name: 'Austin-Bergstrom', country: 'USA' },
  { code: 'YYZ', city: 'Toronto', name: 'Pearson Intl', country: 'Canada' },
  { code: 'YVR', city: 'Vancouver', name: 'Vancouver Intl', country: 'Canada' },
  { code: 'YUL', city: 'Montreal', name: 'Pierre Elliott Trudeau', country: 'Canada' },
  { code: 'YYC', city: 'Calgary', name: 'Calgary Intl', country: 'Canada' },
  { code: 'LHR', city: 'London', name: 'Heathrow', country: 'UK' },
  { code: 'LGW', city: 'London', name: 'Gatwick', country: 'UK' },
  { code: 'STN', city: 'London', name: 'Stansted', country: 'UK' },
  { code: 'MAN', city: 'Manchester', name: 'Manchester', country: 'UK' },
  { code: 'EDI', city: 'Edinburgh', name: 'Edinburgh', country: 'UK' },
  { code: 'DUB', city: 'Dublin', name: 'Dublin', country: 'Ireland' },
  { code: 'CDG', city: 'Paris', name: 'Charles de Gaulle', country: 'France' },
  { code: 'ORY', city: 'Paris', name: 'Orly', country: 'France' },
  { code: 'NCE', city: 'Nice', name: "Côte d'Azur", country: 'France' },
  { code: 'AMS', city: 'Amsterdam', name: 'Schiphol', country: 'Netherlands' },
  { code: 'FRA', city: 'Frankfurt', name: 'Frankfurt Main', country: 'Germany' },
  { code: 'MUC', city: 'Munich', name: 'Munich', country: 'Germany' },
  { code: 'BER', city: 'Berlin', name: 'Brandenburg', country: 'Germany' },
  { code: 'ZRH', city: 'Zurich', name: 'Zurich', country: 'Switzerland' },
  { code: 'GVA', city: 'Geneva', name: 'Geneva', country: 'Switzerland' },
  { code: 'VIE', city: 'Vienna', name: 'Vienna Intl', country: 'Austria' },
  { code: 'MAD', city: 'Madrid', name: 'Barajas', country: 'Spain' },
  { code: 'BCN', city: 'Barcelona', name: 'El Prat', country: 'Spain' },
  { code: 'LIS', city: 'Lisbon', name: 'Humberto Delgado', country: 'Portugal' },
  { code: 'FCO', city: 'Rome', name: 'Fiumicino', country: 'Italy' },
  { code: 'MXP', city: 'Milan', name: 'Malpensa', country: 'Italy' },
  { code: 'VCE', city: 'Venice', name: 'Marco Polo', country: 'Italy' },
  { code: 'ATH', city: 'Athens', name: 'Eleftherios Venizelos', country: 'Greece' },
  { code: 'IST', city: 'Istanbul', name: 'Istanbul', country: 'Turkey' },
  { code: 'ASR', city: 'Cappadocia', name: 'Kayseri Erkilet', country: 'Turkey' },
  { code: 'SVO', city: 'Moscow', name: 'Sheremetyevo', country: 'Russia' },
  { code: 'DXB', city: 'Dubai', name: 'Dubai Intl', country: 'UAE' },
  { code: 'AUH', city: 'Abu Dhabi', name: 'Abu Dhabi Intl', country: 'UAE' },
  { code: 'DOH', city: 'Doha', name: 'Hamad Intl', country: 'Qatar' },
  { code: 'RUH', city: 'Riyadh', name: 'King Khalid Intl', country: 'Saudi Arabia' },
  { code: 'JED', city: 'Jeddah', name: 'King Abdulaziz Intl', country: 'Saudi Arabia' },
  { code: 'TLV', city: 'Tel Aviv', name: 'Ben Gurion', country: 'Israel' },
  { code: 'CAI', city: 'Cairo', name: 'Cairo Intl', country: 'Egypt' },
  { code: 'JNB', city: 'Johannesburg', name: 'O. R. Tambo', country: 'South Africa' },
  { code: 'CPT', city: 'Cape Town', name: 'Cape Town Intl', country: 'South Africa' },
  { code: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta', country: 'Kenya' },
  { code: 'DEL', city: 'Delhi', name: 'Indira Gandhi Intl', country: 'India' },
  { code: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji', country: 'India' },
  { code: 'BLR', city: 'Bengaluru', name: 'Kempegowda Intl', country: 'India' },
  { code: 'MAA', city: 'Chennai', name: 'Chennai Intl', country: 'India' },
  { code: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi Intl', country: 'India' },
  { code: 'CCU', city: 'Kolkata', name: 'Netaji Subhas Chandra Bose', country: 'India' },
  { code: 'COK', city: 'Kochi', name: 'Cochin Intl', country: 'India' },
  { code: 'GOI', city: 'Goa', name: 'Dabolim', country: 'India' },
  { code: 'AMD', city: 'Ahmedabad', name: 'Sardar Vallabhbhai Patel', country: 'India' },
  { code: 'PNQ', city: 'Pune', name: 'Pune Airport', country: 'India' },
  { code: 'JAI', city: 'Jaipur', name: 'Jaipur Intl', country: 'India' },
  { code: 'LKO', city: 'Lucknow', name: 'Chaudhary Charan Singh Intl', country: 'India' },
  { code: 'IXC', city: 'Chandigarh', name: 'Chandigarh Intl', country: 'India' },
  { code: 'ATQ', city: 'Amritsar', name: 'Sri Guru Ram Dass Jee Intl', country: 'India' },
  { code: 'NAG', city: 'Nagpur', name: 'Dr. Babasaheb Ambedkar Intl', country: 'India' },
  { code: 'IDR', city: 'Indore', name: 'Devi Ahilyabai Holkar', country: 'India' },
  { code: 'BHO', city: 'Bhopal', name: 'Raja Bhoj', country: 'India' },
  { code: 'PAT', city: 'Patna', name: 'Jay Prakash Narayan', country: 'India' },
  { code: 'VNS', city: 'Varanasi', name: 'Lal Bahadur Shastri Intl', country: 'India' },
  { code: 'GAU', city: 'Guwahati', name: 'Lokpriya Gopinath Bordoloi Intl', country: 'India' },
  { code: 'BBI', city: 'Bhubaneswar', name: 'Biju Patnaik Intl', country: 'India' },
  { code: 'TRV', city: 'Trivandrum', name: 'Thiruvananthapuram Intl', country: 'India' },
  { code: 'CJB', city: 'Coimbatore', name: 'Coimbatore Intl', country: 'India' },
  { code: 'IXM', city: 'Madurai', name: 'Madurai Airport', country: 'India' },
  { code: 'IXE', city: 'Mangalore', name: 'Mangaluru Intl', country: 'India' },
  { code: 'VTZ', city: 'Visakhapatnam', name: 'Visakhapatnam Intl', country: 'India' },
  { code: 'IXR', city: 'Ranchi', name: 'Birsa Munda', country: 'India' },
  { code: 'IXB', city: 'Bagdogra', name: 'Bagdogra (Siliguri)', country: 'India' },
  { code: 'SXR', city: 'Srinagar', name: 'Sheikh ul-Alam Intl', country: 'India' },
  { code: 'IXL', city: 'Leh', name: 'Kushok Bakula Rimpochee', country: 'India' },
  { code: 'IXZ', city: 'Port Blair', name: 'Veer Savarkar Intl', country: 'India' },
  { code: 'CMB', city: 'Colombo', name: 'Bandaranaike Intl', country: 'Sri Lanka' },
  { code: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal', country: 'Bangladesh' },
  { code: 'KTM', city: 'Kathmandu', name: 'Tribhuvan Intl', country: 'Nepal' },
  { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi', country: 'Thailand' },
  { code: 'DMK', city: 'Bangkok', name: 'Don Mueang', country: 'Thailand' },
  { code: 'HKT', city: 'Phuket', name: 'Phuket Intl', country: 'Thailand' },
  { code: 'SIN', city: 'Singapore', name: 'Changi', country: 'Singapore' },
  { code: 'KUL', city: 'Kuala Lumpur', name: 'KLIA', country: 'Malaysia' },
  { code: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta', country: 'Indonesia' },
  { code: 'DPS', city: 'Bali', name: 'Ngurah Rai', country: 'Indonesia' },
  { code: 'MNL', city: 'Manila', name: 'Ninoy Aquino', country: 'Philippines' },
  { code: 'HAN', city: 'Hanoi', name: 'Noi Bai', country: 'Vietnam' },
  { code: 'SGN', city: 'Ho Chi Minh City', name: 'Tan Son Nhat', country: 'Vietnam' },
  { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong Intl', country: 'Hong Kong' },
  { code: 'TPE', city: 'Taipei', name: 'Taoyuan', country: 'Taiwan' },
  { code: 'ICN', city: 'Seoul', name: 'Incheon Intl', country: 'South Korea' },
  { code: 'GMP', city: 'Seoul', name: 'Gimpo Intl', country: 'South Korea' },
  { code: 'NRT', city: 'Tokyo', name: 'Narita', country: 'Japan' },
  { code: 'HND', city: 'Tokyo', name: 'Haneda', country: 'Japan' },
  { code: 'KIX', city: 'Osaka', name: 'Kansai Intl', country: 'Japan' },
  { code: 'ITM', city: 'Osaka', name: 'Itami', country: 'Japan' },
  { code: 'CTS', city: 'Sapporo', name: 'New Chitose', country: 'Japan' },
  { code: 'UKB', city: 'Kyoto', name: 'Kobe (nearest)', country: 'Japan' },
  { code: 'PEK', city: 'Beijing', name: 'Beijing Capital', country: 'China' },
  { code: 'PKX', city: 'Beijing', name: 'Beijing Daxing', country: 'China' },
  { code: 'PVG', city: 'Shanghai', name: 'Pudong', country: 'China' },
  { code: 'SHA', city: 'Shanghai', name: 'Hongqiao', country: 'China' },
  { code: 'CAN', city: 'Guangzhou', name: 'Baiyun', country: 'China' },
  { code: 'SYD', city: 'Sydney', name: 'Kingsford Smith', country: 'Australia' },
  { code: 'MEL', city: 'Melbourne', name: 'Melbourne', country: 'Australia' },
  { code: 'BNE', city: 'Brisbane', name: 'Brisbane', country: 'Australia' },
  { code: 'PER', city: 'Perth', name: 'Perth', country: 'Australia' },
  { code: 'AKL', city: 'Auckland', name: 'Auckland', country: 'New Zealand' },
  { code: 'GRU', city: 'São Paulo', name: 'Guarulhos', country: 'Brazil' },
  { code: 'GIG', city: 'Rio de Janeiro', name: 'Galeão', country: 'Brazil' },
  { code: 'EZE', city: 'Buenos Aires', name: 'Ezeiza', country: 'Argentina' },
  { code: 'SCL', city: 'Santiago', name: 'Arturo Merino', country: 'Chile' },
  { code: 'LIM', city: 'Lima', name: 'Jorge Chávez', country: 'Peru' },
  { code: 'BOG', city: 'Bogotá', name: 'El Dorado', country: 'Colombia' },
  { code: 'MEX', city: 'Mexico City', name: 'Benito Juárez', country: 'Mexico' },
  { code: 'CUN', city: 'Cancún', name: 'Cancún Intl', country: 'Mexico' },
  { code: 'PTY', city: 'Panama City', name: 'Tocumen', country: 'Panama' },
  { code: 'HAV', city: 'Havana', name: 'José Martí', country: 'Cuba' },
  { code: 'NAS', city: 'Nassau', name: 'Lynden Pindling', country: 'Bahamas' },
  { code: 'ZQN', city: 'Queenstown', name: 'Queenstown', country: 'New Zealand' },
  { code: 'ZRH', city: 'Matterhorn', name: 'Zurich (nearest)', country: 'Switzerland' },
];

export function searchAirports(q: string, limit = 8): Airport[] {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  return AIRPORTS.filter((a) => {
    const hay = `${a.code} ${a.city} ${a.name} ${a.country}`.toLowerCase();
    return hay.includes(s);
  }).slice(0, limit);
}
